default:
  image: python:3.12 # Use a suitable Python version
  before_script:
    - python --version
    - pip install poetry # Install Poetry in the CI environment
    - poetry config virtualenvs.in-project true # Create virtualenv in project directory
    - poetry install --without dev # Install production dependencies first (optional, but good practice)
    - poetry install --with dev # Install dev dependencies (including pytest-cov)

stages:
  - test
  - build
  - publish

test:
  stage: test
  script:
    - poetry run pytest --cov=./src --cov-report=term --cov-report=xml:coverage.xml --junitxml=report.xml
    # Replace 'your_project_folder' with the actual folder name of your Python source code.
    # If your source code is directly in the root, you might use '.' or your package name.
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/' # Regex to extract coverage percentage
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.xml # Also upload the XML report as a regular artifact (optional, for debugging/download)

build:
  stage: build
  script:
    # Extract version from git tag (remove 'v' prefix) if tag exists
    - if [ -n "$CI_COMMIT_TAG" ]; then export VERSION=${CI_COMMIT_TAG#v}; fi
    # Update version in pyproject.toml if tag exists
    - if [ -n "$CI_COMMIT_TAG" ]; then poetry version $VERSION; fi
    # Build the package
    - poetry build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

publish:
  stage: publish
  script:
    # Extract version from git tag (remove 'v' prefix)
    - export VERSION=${CI_COMMIT_TAG#v}
    # Update version in pyproject.toml
    - poetry version $VERSION
    # Configure PyPI credentials
    - poetry config pypi-token.pypi $PYPI_TOKEN
    # Publish to PyPI
    - poetry publish --no-interaction
  dependencies:
    - build
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
      # Only run when tag matches the format v1.0.0
